<x-app-layout>
<x-slot name="header">Business tools · Timesheets</x-slot>
<x-dashboard.page-header eyebrow="Weekly approvals" title="Submit and lock a complete working week" description="A submitted week is ready for review. Approved entries stay locked until an authorised reviewer reopens them." />
<x-tools.navigation area="business" :$access :$canPayroll />

<form method="GET" action="{{ route('business.timesheets.index') }}" class="tool-week-selector"><label>Review week beginning<input type="date" name="week" value="{{ $selectedWeek->toDateString() }}"></label><button class="dashboard-button dashboard-button--secondary">Load week</button></form>
<section class="tool-readiness-summary {{ $currentWeekEntryCount > 0 ? 'is-ready' : '' }}"><span><x-dashboard.icon :name="$currentWeekEntryCount > 0 ? 'check' : 'pending'" :size="20" /></span><div><strong>Week of {{ $selectedWeek->format('d M') }} has {{ $currentWeekEntryCount }} {{ str('entry')->plural($currentWeekEntryCount) }}</strong><small>{{ intdiv($currentWeekMinutes,60) }}h {{ str_pad((string)($currentWeekMinutes%60),2,'0',STR_PAD_LEFT) }}m recorded · an empty week cannot be submitted.</small></div><a wire:navigate href="{{ route('hours.index') }}">Review hours<x-dashboard.icon name="arrow" :size="15" /></a></section>

<section class="dashboard-panel tool-module-panel"><div class="dashboard-panel-heading"><div><p class="dashboard-eyebrow">Approval ledger</p><h2>Weekly timesheets</h2></div><span>Approved entries are locked</span></div>
@if(!$access['timesheet_approvals'])<x-pro.locked feature="timesheet approvals" />@else
<form method="POST" action="{{ route('business.timesheets.submit') }}" class="pro-inline-form tool-timesheet-form">@csrf<label>Week beginning<input type="date" name="week_start" value="{{ old('week_start',$selectedWeek->toDateString()) }}" required></label><label>Submission note<input name="submission_note" value="{{ old('submission_note') }}"></label><button class="dashboard-button dashboard-button--primary" @disabled($currentWeekEntryCount===0)>Submit selected week</button></form>
@error('week_start')<p class="tool-form-error">{{ $message }}</p>@enderror
<div class="business-table-wrap"><table><thead><tr><th>Member</th><th>Week</th><th>Status</th><th>Reviewed by</th><th>Action</th></tr></thead><tbody>@forelse($timesheets as $sheet)<tr><td>{{ $sheet->user->name }}</td><td>{{ $sheet->week_start->format('d M Y') }}</td><td><span class="business-status is-{{ $sheet->status }}">{{ str($sheet->status)->headline() }}</span></td><td>{{ $sheet->reviewer?->name ?? '—' }}</td><td>@if($canReview)<form method="POST" action="{{ route('business.timesheets.review',$sheet) }}" data-confirm="Apply this timesheet decision? Approved weeks will be locked until they are audited and reopened." data-confirm-tone="neutral">@csrf<select name="decision">@if($sheet->status==='submitted')<option value="approved">Approve & lock</option><option value="rejected">Reject</option>@else<option value="reopened">Reopen</option>@endif</select><input name="review_note" placeholder="Optional note"><button>Apply</button></form>@else—@endif</td></tr>@empty<tr><td colspan="5"><x-tools.empty-state icon="timesheet" title="No timesheets yet" description="Log time during a week, then submit that week for review." /></td></tr>@endforelse</tbody></table></div>@endif</section>
</x-app-layout>
