<section class="dashboard-panel security-card settings-card">
    <header><div><p class="dashboard-eyebrow">Active access</p><h2>Browser sessions</h2><p>Review and sign out sessions on your other browsers and devices.</p></div><span class="security-status">{{ count($this->sessions) }} sessions</span></header>
    <div class="security-card__body">
        <p class="settings-card__lead">If you do not recognise a session, sign it out and update your password immediately.</p>
        @if(count($this->sessions)>0)<div class="session-list">@foreach($this->sessions as $session)<article><span><x-dashboard.icon :name="$session->agent->isDesktop() ? 'overview' : 'settings'" /></span><div><strong>{{ $session->agent->platform() ?: 'Unknown' }} · {{ $session->agent->browser() ?: 'Unknown' }}</strong><small>{{ $session->ip_address }} @if($session->is_current_device)<b>This device</b>@else · Last active {{ $session->last_active }}@endif</small></div></article>@endforeach</div>@endif
        <div class="settings-form__actions settings-form__actions--start"><x-action-message on="loggedOut">Done.</x-action-message><button type="button" class="dashboard-button dashboard-button--secondary" wire:click="confirmLogout" wire:loading.attr="disabled">Log out other browser sessions</button></div>
    </div>
    <x-dialog-modal wire:model.live="confirmingLogout"><x-slot name="title">Log out other browser sessions</x-slot><x-slot name="content">Enter your password to confirm.<div class="confirm-password-field" x-data="{}" x-on:confirming-logout-other-browser-sessions.window="setTimeout(()=>$refs.password.focus(),250)"><x-input type="password" autocomplete="current-password" placeholder="Password" x-ref="password" wire:model="password" wire:keydown.enter="logoutOtherBrowserSessions"/><x-input-error for="password"/></div></x-slot><x-slot name="footer"><x-secondary-button wire:click="$toggle('confirmingLogout')">Cancel</x-secondary-button><x-button class="ms-3" wire:click="logoutOtherBrowserSessions" wire:loading.attr="disabled">Log out sessions</x-button></x-slot></x-dialog-modal>
</section>
