<x-app-layout>
<x-slot name="header">Pro tools</x-slot>
<x-dashboard.page-header eyebrow="Workspace growth suite" title="Turn tracked time into useful work" description="Manage clients, pay rates, schedule suggestions, reports, integrations and invoices without changing historical records." />

<nav class="pro-tool-nav" aria-label="Pro tools"><a href="#clients">Clients</a><a href="#earnings">Earnings</a><a href="#schedules">Schedules</a><a href="#reports">Reports</a><a href="#integrations">Calendars</a><a href="#invoices">Invoices</a></nav>

<section id="clients" class="dashboard-panel pro-tool-panel">
<div class="dashboard-panel-heading"><div><p class="dashboard-eyebrow">Clients & projects</p><h2>Organise billable work</h2></div><span>{{ $clients->count() }} clients · {{ $projects->count() }} projects</span></div>
@if(!$access['clients_projects'])<x-pro.locked feature="clients and projects" />@else
<div class="pro-tool-grid"><form method="POST" action="{{ route('pro.clients.store') }}" class="pro-compact-form">@csrf<h3>Add client</h3><label>Name<input name="name" required maxlength="100"></label><label>Email<input type="email" name="email"></label><label>Address<textarea name="address"></textarea></label><button class="dashboard-button dashboard-button--primary">Create client</button></form>
<form method="POST" action="{{ route('pro.projects.store') }}" class="pro-compact-form">@csrf<h3>Add project</h3><label>Client<select name="client_id"><option value="">Internal / no client</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select></label><label>Name<input name="name" required></label><div><label>Code<input name="code"></label><label>Billable rate (£/hour)<input type="number" step=".01" min="0" name="hourly_rate"></label></div><button class="dashboard-button dashboard-button--primary">Create project</button></form></div>
<div class="pro-record-list">@forelse($projects as $project)<article><span class="pro-avatar">{{ str($project->name)->substr(0,1)->upper() }}</span><div><strong>{{ $project->name }}</strong><small>{{ $project->client?->name ?? 'Internal' }}{{ $project->code?' · '.$project->code:'' }}</small></div><b>{{ $project->hourly_rate_minor!==null?'£'.number_format($project->hourly_rate_minor/100,2).'/h':'No client rate' }}</b><form method="POST" action="{{ route('pro.projects.destroy',$project) }}" data-confirm="Archive this project?">@csrf @method('DELETE')<button>Archive</button></form></article>@empty<p>No projects yet.</p>@endforelse</div>
@endif</section>

<section id="earnings" class="dashboard-panel pro-tool-panel"><div class="dashboard-panel-heading"><div><p class="dashboard-eyebrow">Effective pay rates</p><h2>Historically stable earnings</h2></div><span>{{ $workspace->currency }}</span></div>
@if(!$access['earnings'])<x-pro.locked feature="earnings and pay rates" />@else
<form method="POST" action="{{ route('pro.rates.store') }}" class="pro-inline-form">@csrf<label>Effective from<input type="date" name="effective_from" required></label><label>Effective to<input type="date" name="effective_to"></label><label>Hourly rate (£)<input type="number" name="hourly_rate" min="0" step=".01" required></label><label>Overtime multiplier<input type="number" name="overtime_multiplier" min="1" max="5" step=".05" value="1.5" required></label><button class="dashboard-button dashboard-button--primary">Save rate</button></form>
<div class="pro-rate-timeline">@forelse($rates as $rate)<article><strong>£{{ number_format($rate->hourly_rate_minor/100,2) }}/hour</strong><span>{{ $rate->effective_from->format('d M Y') }} → {{ $rate->effective_to?->format('d M Y') ?? 'ongoing' }}</span><small>{{ number_format($rate->overtime_multiplier_bps/10000,2) }}× overtime snapshot</small></article>@empty<p>Add your first effective rate. Existing worked entries are never silently recalculated.</p>@endforelse</div>@endif</section>

<section id="schedules" class="dashboard-panel pro-tool-panel"><div class="dashboard-panel-heading"><div><p class="dashboard-eyebrow">Recurring schedules</p><h2>Expected shifts, never fake hours</h2></div><span>{{ $schedules->count() }} suggestions</span></div>
@if(!$access['recurring_schedules'])<x-pro.locked feature="recurring schedules" />@else
<form method="POST" action="{{ route('pro.schedules.store') }}" class="pro-inline-form">@csrf<label>Weekday<select name="day_of_week">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $i=>$day)<option value="{{ $i+1 }}">{{ $day }}</option>@endforeach</select></label><label>Start<input type="time" name="start_time" value="09:00" required></label><label>End<input type="time" name="end_time" value="17:30" required></label><label>Break minutes<input type="number" name="break_minutes" value="30" min="0" required></label><label>Break type<select name="break_type"><option value="unpaid">Unpaid</option><option value="paid">Paid</option></select></label><button class="dashboard-button dashboard-button--primary">Add suggestion</button></form>
<div class="pro-record-list">@foreach($schedules as $schedule)<article><span class="pro-avatar">{{ ['M','T','W','T','F','S','S'][$schedule->day_of_week-1] }}</span><div><strong>{{ Carbon\CarbonImmutable::now()->startOfWeek()->addDays($schedule->day_of_week-1)->format('l') }} · {{ substr($schedule->start_time,0,5) }}–{{ substr($schedule->end_time,0,5) }}</strong><small>{{ $schedule->break_minutes }}m {{ $schedule->break_type }} break · user confirms every conversion</small></div><form method="POST" action="{{ route('pro.schedules.convert',$schedule) }}">@csrf<input type="date" name="work_date" required><button>Convert to entry</button></form></article>@endforeach</div>@endif</section>

<section class="dashboard-panel pro-tool-panel"><div class="dashboard-panel-heading"><div><p class="dashboard-eyebrow">Smart reminders</p><h2>Useful nudges, under your control</h2></div></div>
@if(!$access['smart_reminders'])<x-pro.locked feature="smart reminders" />@else<form method="POST" action="{{ route('pro.reminders.update') }}" class="pro-reminder-form">@csrf @method('PUT')<div>@foreach(['missing_entry'=>'Missing hours','weekly_target'=>'Weekly target','overtime'=>'Overtime reached','trial_ending'=>'Trial ending','payment_failed'=>'Payment failed'] as $key=>$label)<label><input type="checkbox" name="types[]" value="{{ $key }}" @checked($preferences->get($key)?->enabled)> {{ $label }}</label>@endforeach</div><div><label><input type="checkbox" name="email" value="1" checked> Email</label><label><input type="checkbox" name="in_app" value="1" checked> In app</label><button class="dashboard-button dashboard-button--primary">Save reminders</button></div></form>@endif</section>

<section id="reports" class="dashboard-panel pro-tool-panel"><div class="dashboard-panel-heading"><div><p class="dashboard-eyebrow">Report automation</p><h2>Reusable and scheduled reports</h2></div><span>{{ $templates->count() }} templates</span></div>
@if(!$access['export_templates'])<x-pro.locked feature="report templates" />@else<form method="POST" action="{{ route('pro.templates.store') }}" class="pro-inline-form">@csrf<label>Template name<input name="name" required></label><label>Format<select name="format"><option value="xlsx">Excel</option><option value="pdf">PDF</option><option value="csv">CSV</option></select></label><button class="dashboard-button dashboard-button--primary">Save template</button></form><div class="pro-record-list">@foreach($templates as $template)<article><span class="pro-avatar">{{ str($template->format)->upper() }}</span><div><strong>{{ $template->name }}</strong><small>{{ collect($template->columns)->join(', ') ?: 'Standard columns' }} · {{ $template->schedules->count() }} schedules</small></div>@if($access['scheduled_reports'])<form method="POST" action="{{ route('pro.templates.schedule',$template) }}">@csrf<select name="frequency"><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select><input name="recipients" type="email" value="{{ auth()->user()->email }}" required><button>Schedule</button></form>@endif</article>@endforeach</div>@endif</section>

<section id="integrations" class="dashboard-panel pro-tool-panel"><div class="dashboard-panel-heading"><div><p class="dashboard-eyebrow">Calendar integrations</p><h2>Review events before logging time</h2></div><span>{{ $connections->count() }}/{{ $access['calendar_integrations']?app(App\Services\FeatureAccess::class)->value(auth()->user(),'calendar_integrations',$workspace):0 }} connected</span></div>@if(!$access['calendar_integrations'])<x-pro.locked feature="calendar integrations" />@else
<div class="calendar-provider-grid">@foreach(['google'=>'Google Calendar','microsoft'=>'Microsoft Outlook'] as $provider=>$label)@php($connection=$connections->firstWhere('provider',$provider))<article><strong>{{ $label }}</strong><p>Imported events stay as suggestions until you explicitly convert them.</p>@if($connection)<span>{{ $connection->events_count }} waiting · last synced {{ $connection->last_synced_at?->diffForHumans() ?? 'never' }}</span><div class="calendar-provider-actions"><form method="POST" action="{{ route('pro.calendars.sync',$connection) }}">@csrf<button class="dashboard-button dashboard-button--secondary">Refresh events</button></form><form method="POST" action="{{ route('pro.calendars.disconnect',$connection) }}" data-confirm="Disconnect this calendar? Confirmed hours will be retained.">@csrf @method('DELETE')<button class="dashboard-button dashboard-button--danger">Disconnect</button></form></div>@else<a class="dashboard-button dashboard-button--primary" href="{{ route('pro.calendars.redirect',$provider) }}">Connect {{ $label }}</a>@endif</article>@endforeach</div>
@foreach($connections as $connection)@if($connection->events->isNotEmpty())<div class="calendar-suggestion-list"><header><strong>{{ str($connection->provider)->headline() }} suggestions</strong><span>Review before adding to worked hours</span></header>@foreach($connection->events as $event)<article><div><strong>{{ $event->summary }}</strong><small>{{ $event->starts_at->timezone(config('hours.timezone'))->format('D, d M Y · H:i') }}–{{ $event->ends_at->timezone(config('hours.timezone'))->format('H:i') }}</small></div><div><form method="POST" action="{{ route('pro.calendars.events.convert',$event) }}">@csrf<input type="hidden" name="break_minutes" value="0"><input type="hidden" name="break_type" value="unpaid"><button class="dashboard-button dashboard-button--primary">Add as hours</button></form><form method="POST" action="{{ route('pro.calendars.events.ignore',$event) }}">@csrf<button class="dashboard-button dashboard-button--secondary">Ignore</button></form></div></article>@endforeach</div>@endif @endforeach
@endif</section>

<section id="invoices" class="dashboard-panel pro-tool-panel"><div class="dashboard-panel-heading"><div><p class="dashboard-eyebrow">Client invoices</p><h2>Snapshot time and rates once</h2></div><span>{{ $invoices->count() }} recent</span></div>
@if(!$access['invoicing'])<x-pro.locked feature="client invoicing" />@else<form method="POST" action="{{ route('pro.invoices.store') }}" class="pro-inline-form">@csrf<label>Client<select name="client_id" required>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select></label><label>From<input type="date" name="start" required></label><label>To<input type="date" name="end" required></label><label>Due date<input type="date" name="due_on" required></label><label>Tax %<input type="number" name="tax_percent" min="0" max="100" step=".01" value="0" required></label><button class="dashboard-button dashboard-button--primary">Create draft</button></form><div class="pro-record-list">@forelse($invoices as $invoice)<a wire:navigate href="{{ route('pro.invoices.show',$invoice) }}"><span class="pro-avatar">£</span><div><strong>{{ $invoice->number }} · {{ $invoice->client?->name }}</strong><small>{{ str($invoice->status)->headline() }} · due {{ $invoice->due_on?->format('d M Y') ?? 'not set' }}</small></div><b>£{{ number_format($invoice->total_minor/100,2) }}</b></a>@empty<p>No invoices yet. Add billable project hours first.</p>@endforelse</div>@endif</section>
</x-app-layout>
