<x-app-layout>
<x-slot name="header">Pro tools · Reminders</x-slot>
<x-dashboard.page-header eyebrow="Smart reminders" title="Choose the nudges that protect your week" description="Control which events matter and whether they reach your inbox, your in-app notifications, or both." />
<x-tools.navigation area="pro" :$access />
<section class="dashboard-panel tool-module-panel"><div class="dashboard-panel-heading"><div><p class="dashboard-eyebrow">Notification rules</p><h2>Reminder preferences</h2></div><span>Under your control</span></div>
@if(!$access['smart_reminders'])<x-pro.locked feature="smart reminders" />@else
@php($selectedReminderTypes = old('types', $preferences->filter(fn ($preference) => $preference->enabled)->keys()->all()))
@php($savedReminderChannels = collect($preferences->first()?->channels ?? ['mail', 'database']))
<form method="POST" action="{{ route('pro.reminders.update') }}" class="pro-reminder-form">@csrf @method('PUT')<fieldset><legend>Notify me when</legend><p>Choose moments where a useful nudge helps you stay on track.</p><div class="pro-reminder-trigger-grid">@foreach(['missing_entry'=>'Missing hours','weekly_target'=>'Weekly target','overtime'=>'Overtime reached','trial_ending'=>'Trial ending','payment_failed'=>'Payment failed'] as $key=>$label)<label class="business-check-option"><input type="checkbox" name="types[]" value="{{ $key }}" @checked(in_array($key,$selectedReminderTypes,true))><span class="business-check-option__box" aria-hidden="true"><svg viewBox="0 0 16 16"><path d="m4 8 2.5 2.5L12 5"/></svg></span><span>{{ $label }}</span></label>@endforeach</div></fieldset><div class="pro-reminder-footer"><fieldset><legend>Delivery channels</legend><div class="pro-reminder-channels"><label class="ui-switch"><input type="checkbox" role="switch" name="email" value="1" @checked(old('email',$savedReminderChannels->contains('mail')))><span class="ui-switch__track" aria-hidden="true"><span></span></span><span><strong>Email</strong><small>Receive reminders in your inbox.</small></span></label><label class="ui-switch"><input type="checkbox" role="switch" name="in_app" value="1" @checked(old('in_app',$savedReminderChannels->contains('database')))><span class="ui-switch__track" aria-hidden="true"><span></span></span><span><strong>In app</strong><small>Keep notifications inside myhourspay.</small></span></label></div></fieldset><button class="dashboard-button dashboard-button--primary">Save reminders</button></div></form>@endif</section>
</x-app-layout>
