<x-app-layout>
<x-slot name="header">Pro tools · Schedules</x-slot>
<x-dashboard.page-header eyebrow="Recurring schedules" title="Plan expected shifts without creating fake hours" description="A schedule is only a suggestion. You explicitly choose the date before it becomes a worked-hours entry." />
<x-tools.navigation area="pro" :$access />
<section class="dashboard-panel tool-module-panel"><div class="dashboard-panel-heading"><div><p class="dashboard-eyebrow">Expected week</p><h2>Schedule suggestions</h2></div><span>{{ $schedules->count() }} active</span></div>
@if(!$access['recurring_schedules'])<x-pro.locked feature="recurring schedules" />@else
<form method="POST" action="{{ route('pro.schedules.store') }}" class="pro-inline-form tool-schedule-form">@csrf<label>Project<select name="project_id"><option value="">No project</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((string)old('project_id')===(string)$project->id)>{{ $project->name }}</option>@endforeach</select></label><label>Weekday<select name="day_of_week">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $i=>$day)<option value="{{ $i+1 }}" @selected((int)old('day_of_week',1)===$i+1)>{{ $day }}</option>@endforeach</select></label><label>Start<input type="time" name="start_time" value="{{ old('start_time','09:00') }}" required></label><label>End<input type="time" name="end_time" value="{{ old('end_time','17:30') }}" required></label><label>Break minutes<input type="number" name="break_minutes" value="{{ old('break_minutes',30) }}" min="0" required></label><label>Break type<select name="break_type"><option value="unpaid" @selected(old('break_type','unpaid')==='unpaid')>Unpaid</option><option value="paid" @selected(old('break_type')==='paid')>Paid</option></select></label><button class="dashboard-button dashboard-button--primary">Add suggestion</button></form>
<div class="pro-record-list">@forelse($schedules as $schedule)<article><span class="pro-avatar">{{ ['M','T','W','T','F','S','S'][$schedule->day_of_week-1] }}</span><div><strong>{{ Carbon\CarbonImmutable::now()->startOfWeek()->addDays($schedule->day_of_week-1)->format('l') }} · {{ substr($schedule->start_time,0,5) }}–{{ substr($schedule->end_time,0,5) }}</strong><small>{{ $schedule->project?->name ?? 'No project' }} · {{ $schedule->break_minutes }}m {{ $schedule->break_type }} break</small></div><form method="POST" action="{{ route('pro.schedules.convert',$schedule) }}">@csrf<input type="date" name="work_date" required><button>Convert to entry</button></form></article>@empty<x-tools.empty-state icon="schedules" title="No schedule suggestions" description="Add an expected shift, then convert it only on a date you actually worked." />@endforelse</div>@endif</section>
</x-app-layout>
