@extends('layouts.admin')
@section('title', $user->name)
@section('content')
<a class="admin-context-back" href="{{ route('admin.users.index') }}"><svg viewBox="0 0 20 20"><path d="m12.5 5-5 5 5 5"/></svg>Back to users</a>
<div class="admin-columns admin-columns--detail">
<section class="admin-card admin-form-card"><header><div><h2>Account details</h2><p>{{ $user->is_admin ? 'Platform administrator' : 'Customer account' }}</p></div><span class="status-pill {{ $user->suspended_at ? 'is-suspended' : 'is-active' }}">{{ $user->suspended_at ? 'Suspended' : 'Active' }}</span></header><form method="POST" action="{{ route('admin.users.update',$user) }}">@csrf @method('PUT')<label>Name<input name="name" value="{{ old('name',$user->name) }}" required></label><label>Email<input type="email" name="email" value="{{ old('email',$user->email) }}" required></label><button>Save user</button></form>@unless(auth()->user()->is($user))<div class="admin-detail-actions"><form method="POST" action="{{ route('admin.users.suspension',$user) }}">@csrf<button>{{ $user->suspended_at ? 'Reactivate user' : 'Suspend user' }}</button></form><form method="POST" action="{{ route('admin.users.verification',$user) }}">@csrf<button>{{ $user->email_verified_at?'Revoke verification':'Verify user' }}</button></form><form method="POST" action="{{ route('admin.users.workspace-reset',$user) }}" data-confirm="Require a new workspace setup?">@csrf<button>Reset workspace</button></form><form method="POST" action="{{ route('admin.users.destroy',$user) }}" data-confirm="Move user to trash?">@csrf @method('DELETE')<button class="is-danger">Move to trash</button></form></div>@endunless</section>
<section class="admin-card"><header><div><h2>Workspace memberships</h2><p>{{ $user->workspaces->count() }} total</p></div></header><div class="admin-list">@forelse($user->workspaces as $workspace)<a href="{{ route('admin.workspaces.show',$workspace) }}"><span class="admin-avatar">{{ str($workspace->name)->substr(0,1)->upper() }}</span><span><strong>{{ $workspace->name }}</strong><small>{{ $workspace->pivot->position }} · {{ $workspace->pivot->role }}</small></span></a>@empty<p>No workspaces.</p>@endforelse</div></section>
</div>
<section class="admin-card admin-table-card"><header><div><h2>Recent hours</h2><p>Read-only activity</p></div></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Date</th><th>Workspace</th><th>Time</th><th>Break</th><th>Net</th></tr></thead><tbody>@forelse($entries as $entry)<tr><td>{{ $entry['work_date'] }}</td><td>{{ $user->hoursEntries->firstWhere('id',$entry['id'])?->workspace?->name }}</td><td>{{ $entry['start_time'] }}–{{ $entry['end_time'] }}</td><td>{{ $entry['break_minutes'] }}m {{ $entry['break_type'] }}</td><td><strong>{{ $entry['net_formatted'] }}</strong></td></tr>@empty<tr><td colspan="5">No hours entries.</td></tr>@endforelse</tbody></table></div></section>
@endsection
