@extends('layouts.admin')
@section('title', 'Campaign details')
@section('content')
<a class="admin-context-back" wire:navigate href="{{ route('admin.marketing.index') }}"><x-admin.icon name="back"/>Back to marketing emails</a>
<section class="admin-card marketing-section"><div class="marketing-heading"><div><p class="dashboard-eyebrow">{{ $campaign->kind === 'intro' ? 'Introductory journey · Day '.$campaign->day : 'Monthly feature update' }}</p><h2>{{ $campaign->subject }}</h2><p>Audience: {{ $campaign->audience }} · Version {{ $campaign->version }}</p></div><span class="marketing-status {{ $campaign->status === 'active' ? 'is-active' : '' }}">{{ ucfirst($campaign->status) }}</span></div>
<div class="marketing-actions"><a class="dashboard-button dashboard-button--secondary" target="_blank" rel="noopener" href="{{ route('admin.marketing.preview', $campaign) }}">Preview email</a><a class="dashboard-button dashboard-button--secondary" href="{{ route('admin.marketing.edit', [$campaign, 'audience' => 1]) }}">Check audience</a><form method="POST" action="{{ route('admin.marketing.test', $campaign) }}">@csrf<button class="dashboard-button dashboard-button--secondary">Send test to my email</button></form><form method="POST" action="{{ route('admin.marketing.state', $campaign) }}">@csrf<input type="hidden" name="status" value="{{ $campaign->status === 'active' ? 'paused' : 'active' }}"><button class="admin-primary-action">{{ $campaign->status === 'active' ? 'Pause campaign' : 'Publish / enable campaign' }}</button></form></div>
@if($counts !== null)<div class="marketing-audience"><h3>Current audience check</h3><p>This check does not enroll users or send email. Timing, consent and access are checked again before sending.</p><dl>@forelse($counts as $reason => $count)<div><dt>{{ $reason }}</dt><dd>{{ $count }}</dd></div>@empty<div><dt>No recorded preferences yet</dt><dd>0</dd></div>@endforelse</dl><details><summary>First 20 accounts and nominal schedule</summary><ul>@foreach($recipients as $recipient)<li>{{ $recipient["email"] }} — {{ $recipient["reason"] }}<br><small>{{ $recipient["due"] }}</small></li>@endforeach</ul></details></div>@endif
</section>
<section class="admin-card marketing-section"><h2>Approved copy</h2><p>Plain text only. The action leads to the appropriate feature or plans page based on the recipient’s access. Saved delivery snapshots are not rewritten.</p>
@php($editable = $campaign->status === 'paused' && !($campaign->kind === 'monthly' && $campaign->published_at))
@unless($editable)<p class="marketing-help">{{ $campaign->kind === 'monthly' && $campaign->published_at ? 'This published update is locked. Create a new monthly campaign for new content.' : 'Pause this campaign before editing.' }}</p>@endunless
<form class="marketing-form" method="POST" action="{{ route('admin.marketing.update', $campaign) }}">@csrf @method('PUT')
<fieldset @disabled(!$editable)><label>Subject<input name="subject" value="{{ old('subject', $campaign->subject) }}" maxlength="150" required></label><label>Preheader<input name="preheader" value="{{ old('preheader', $campaign->preheader) }}" maxlength="200" required></label><label>Heading<input name="heading" value="{{ old('heading', $campaign->heading) }}" maxlength="150" required></label><label>Message<textarea name="body" rows="8" maxlength="4000" required>{{ old('body', $campaign->body) }}</textarea></label><label>Day after enrollment (introduction only)<input name="day" type="number" min="1" max="30" value="{{ old('day', $campaign->day) }}" required></label><button class="admin-primary-action">Save campaign</button></fieldset>
</form></section>
@endsection
